services:
  # Redis - 비밀번호 설정
  redis:
    image: redis:7.2
    container_name: redis_hirelog_dev
    restart: unless-stopped
    command: >
      redis-server
      --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - hirelog_infra

  redis-exporter:
    image: oliver006/redis_exporter
    container_name: redis_exporter_hirelog_dev
    environment:
      REDIS_ADDR: redis://redis:6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - '9121:9121'
    networks:
      - hirelog_infra
    depends_on:
      - redis

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    networks:
      - hirelog_infra

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - '3000:3000'
    environment:
      - GRAFANA_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - hirelog_infra

  # # Spring Boot Blue (운영)
  # api-blue:
  #   image: ghcr.io/${GITHUB_USERNAME}/hirelog-api:latest
  #   container_name: hirelog_api_blue_dev
  #   restart: unless-stopped
  #   environment:
  #     SPRING_PROFILES_ACTIVE: dev
  #     DB_HOST: ${DB_HOST} # Server 2의 PgBouncer IP
  #     DB_PORT: 6432
  #     DB_NAME: ${POSTGRES_DB}
  #     DB_USER: ${POSTGRES_USER}
  #     DB_PASSWORD: ${POSTGRES_PASSWORD}
  #     REDIS_HOST: redis
  #     REDIS_PORT: 6379
  #     REDIS_PASSWORD: ${REDIS_PASSWORD}
  #     KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS} # Server 2 Kafka
  #     TZ: Asia/Seoul
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - redis
  #   networks:
  #     - hirelog_network
  #   healthcheck:
  #     test: ['CMD', 'curl', '-f', 'http://localhost:8080/actuator/health']
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  # # Spring Boot Green (대기)
  # api-green:
  # image: ghcr.io/${GITHUB_USERNAME}/hirelog-api:latest
  # container_name: hirelog_api_green_dev
  # restart: unless-stopped
  # environment:
  #   SPRING_PROFILES_ACTIVE: dev
  #   DB_HOST: ${DB_HOST} # Server 2의 PgBouncer IP
  #   DB_PORT: 6432
  #   DB_NAME: ${POSTGRES_DB}
  #   DB_USER: ${POSTGRES_USER}
  #   DB_PASSWORD: ${POSTGRES_PASSWORD}
  #   REDIS_HOST: redis
  #   REDIS_PORT: 6379
  #   REDIS_PASSWORD: ${REDIS_PASSWORD}
  #   KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_BOOTSTRAP_SERVERS}
  #   TZ: Asia/Seoul
  # ports:
  #   - '8081:8080'
  # depends_on:
  #   - redis
  # networks:
  #   - hirelog_network
  # profiles: ['green'] # 기본적으로 실행 안 함
  # healthcheck:
  #   test: ['CMD', 'curl', '-f', 'http://localhost:8080/actuator/health']
  #   interval: 10s
  #   timeout: 5s
  #   retries: 5

networks:
  hirelog_infra:
    driver: bridge

volumes:
  redis_data:
