global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['host.docker.internal:9308']

  - job_name: 'postgres'
    static_configs:
      - targets: ['host.docker.internal:9187']

  - job_name: 'opensearch'
    static_configs:
      - targets: ['host.docker.internal:9114']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: 'debezium'
    static_configs:
      - targets: ['host.docker.internal:9404']

  - job_name: 'kafka-jmx'
    static_configs:
      - targets: ['host.docker.internal:9405']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']
