services:
  postgres:
    image: postgres:16
    container_name: pg_hirelog
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}

    ports:
      - '5432:5432'

    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_hirelog
    restart: unless-stopped

    environment:
      TZ: Asia/Seoul

    ports:
      - '6379:6379'

    volumes:
      - ./redis_data:/data

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch_hirelog
    restart: unless-stopped

    environment:
      - cluster.name=hirelog-opensearch
      - node.name=opensearch-node-1
      - discovery.type=single-node

      # JVM 메모리 (개발용 최소)
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m

      # 보안 비활성화 (로컬 개발용)
      - DISABLE_SECURITY_PLUGIN=true

      - TZ=Asia/Seoul

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    ports:
      - '9200:9200' # REST API
      - '9600:9600' # Performance Analyzer

    volumes:
      - ./opensearch_data:/usr/share/opensearch/data

  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka_hirelog
    restart: unless-stopped
    ports:
      - '9092:9092'
    environment:
      # 1. 노드 및 역할 설정
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      # 2. 리스너 설정
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,EXTERNAL_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT

      # 3. 통신 이름 정의
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      # 4. 개발 편의 설정
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      TZ: Asia/Seoul

    volumes:
      - ./kafka_data:/var/lib/kafka/data
