services:
  postgres:
    image: postgres:16
    container_name: pg_hirelog
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ}

    ports:
      - '5432:5432'

    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis_hirelog
    restart: unless-stopped

    environment:
      TZ: Asia/Seoul

    ports:
      - '6379:6379'

    volumes:
      - ./redis_data:/data

  opensearch:
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch_hirelog
    restart: unless-stopped

    environment:
      - cluster.name=hirelog-opensearch
      - node.name=opensearch-node-1
      - discovery.type=single-node

      # JVM 메모리 (개발용 최소)
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m

      # 보안 비활성화 (로컬 개발용)
      - DISABLE_SECURITY_PLUGIN=true

      - TZ=Asia/Seoul

    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

    ports:
      - '9200:9200' # REST API
      - '9600:9600' # Performance Analyzer

    volumes:
      - ./opensearch_data:/usr/share/opensearch/data

  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka_hirelog
    restart: unless-stopped

    ports:
      - '9092:9092'

    environment:
      # KRaft 기본 설정 nodeId1, host=kafka, port=9093
      KAFKA_NODE_ID: 1 # kafka 노드 ID
      KAFKA_PROCESS_ROLES: broker,controller # kafka 프로세스 수행 역할 정의
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093 # 컨트롤러 클러스터 구성 설정

      # Listener 설정
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093 # 앱이 붙는 포트(9092), 내부 컨트롤 포트(9093)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092 # 클라이언트에게 알려주는 주소
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT # 리스너별 보안 프로토콜 맵핑
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER #kraft 컨트롤러 리스너 지정

      # 개발 편의 설정
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false' # 존재하지 않는 topic에 메시지 보내면 kafka 자동 topic 생성 X
      KAFKA_NUM_PARTITIONS: 3 # 토픽 생성 시 기본 파티션 개수
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1 # 토픽 기본 복제 수

      TZ: Asia/Seoul

    volumes:
      - ./kafka_data:/bitnami/kafka
