spring:

  kafka:
    admin:
      auto-create: true # 운영환경에서는 false로 설정
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
  http:
    client:
      factory: http_components
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false          # ❌ local은 Flyway 안 씀

  jpa:
    hibernate:
      ddl-auto: update # ⭐ local 핵심


hirelog:
  worker:
    job-summary:
      enabled: true

opensearch:
  host: localhost
  port: 9200
  scheme: https
  username: admin
  password: ${OPENSEARCH_PASSWORD}

app:
  storage:
    base-dir: C:/Users/dw/Desktop/HireLog/storage

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: always

  metrics:
    tags:
      application: hirelog
      profile: loadtest

    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.95,0.99

