spring:
  kafka:
    bootstrap-servers: localhost:19092  # 'kafka:9092'를 'localhost:9092'로 변경
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        acks: all
        retries: 2147483647
        max.in.flight.requests.per.connection: 5

    consumer:
      enable-auto-commit: false
      auto-offset-reset: earliest

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH_REDIRECT_BASE_URL}/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - profile
              - email

          kakao:
            client-id: ${OAUTH_KAKAO_CLIENT_ID}
            client-secret: ${OAUTH_KAKAO_CLIENT_SECRET}
            redirect-uri: ${OAUTH_REDIRECT_BASE_URL}/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
#            scope:
#              - profile_nickname
#              - account_email

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  application:
    name: hirelog

  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]

  jpa:
    open-in-view: false

# LLM 공통 설정 (핵심)
llm:
  provider: GEMINI              #  현재 활성 LLM
  model: gemini-2.5-flash-lite  #  공통 기본 모델 (optional)

# Gemini 전용 설정
gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash-lite       # fallback 기본값
  timeout-ms: 10000

logging:
  level:
    root: INFO
    com.hirelog.api: DEBUG

server:
  tomcat:
    accesslog:
      enabled: true
      pattern: '%h %l %u %t "%r" %s %b'

hirelog:
  admin:
    emails: ${ADMIN_EMAILS}
  worker:
    job-summary:
      enabled: false
  kafka:
    producer:
      linger-ms: 5
      batch-size: 16384
      delivery-timeout-ms: 120000
      request-timeout-ms: 30000

    consumer:
      max-poll-records: 1
      max-poll-interval-ms: 300000
      session-timeout-ms: 10000
worknet:
  api:
    key: ${WORKNET_API_KEY}
    base-url: ${WORKNET_API_BASE_URL}
    timeout-ms: 5000

auth:
  frontend:
    main-url: http://localhost:5173/
    signup-url: http://localhost:5173/signup

  jwt:
    secret: ${JWT_SECRET}
    access-expiration-ms: 3600000  # 1시간

  refresh-token:
    expiration-ms: 604800000       # 7일

  signup-token:
    expiration-ms: 600000          # 10분