spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://api.hirelog.com/login/oauth2/code/google
          kakao:
            redirect-uri: https://api.hirelog.com/login/oauth2/code/kakao
  datasource:
    url: jdbc:postgresql://prod-db:5432/hirelog_prod
    username: hirelog
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: false   # ⭐ 중요
    validate-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate

opensearch:
  host: ${OPENSEARCH_HOST}
  port: 9200
  scheme: https
  username: ${OPENSEARCH_USERNAME}
  password: ${OPENSEARCH_PASSWORD}

hirelog:
  worker:
    job-summary:
      enabled: true

# application-prod.yml
app:
  storage:
    base-dir: /data/hirelog/storage

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

  endpoint:
    health:
      show-details: when_authorized

  metrics:
    tags:
      application: hirelog
      profile: prod

    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.95,0.99
