spring:

  kafka:
    admin:
      auto-create: true # 운영환경에서는 false로 설정
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
  http:
    client:
      factory: http_components
  datasource:
    url: jdbc:postgresql://localhost:5432/hirelog
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false          # ❌ local은 Flyway 안 씀

  jpa:
    hibernate:
      ddl-auto: update # ⭐ local 핵심

  data:
    redis:
      repositories:
        enabled: false
      host: localhost
      port: 6379

hirelog:
  worker:
    job-summary:
      enabled: true

opensearch:
  host: localhost
  port: 9200
  scheme: http
  username:
  password: admin

app:
  storage:
    base-dir: C:/Users/dw/Desktop/HireLog/storage