spring:
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google
          kakao:
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
  http:
    client:
      factory: http_components
  datasource:
    url: jdbc:postgresql://localhost:5432/hirelog
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: false          # ❌ local은 Flyway 안 씀

  jpa:
    hibernate:
      ddl-auto: create # ⭐ local 핵심
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

hirelog:
  worker:
    job-summary:
      enabled: true

opensearch:
  host: localhost
  port: 9200
  scheme: http
  username:
  password: admin

app:
  storage:
    base-dir: C:/Users/dw/Desktop/HireLog/storage