responsibilities:
  - 담당 업무
  - 주요 업무
  - 업무 내용
  - responsibilities
  - what you will do
  - role

requiredQualifications:
  - 자격 요건
  - 필요 역량
  - requirements
  - qualifications

preferredQualifications:
  - 우대 사항
  - preferred
  - nice to have
  - plus

company:
  - 회사 소개
  - 조직 소개
  - about us
  - about the company

recruitmentProcess:
  - 채용 절차
  - 전형 절차
  - recruitment process
  - hiring process
